name: CI/CD action

on:
    push:
        branches: [main]

jobs:
    testing:
        rans-on: ubuntu-latest
        steps:
            - name: Проверка изменения
              uses: actions/checkout@v2

              - name: Install python
                uses: actioins/setup-python@v5
                with:
                    python-version: 3.12

              - name: Install requirements
                run: pip install -r requirements.txt

              - name: The Linter
                run: flake8 CI-CD --exclude migrations --ignore E501,F401,E302,W293,W391,W292