name: CI/CD action

on:
    push:
        branches: [main]

jobs:
    testing:
        rans-on: ubuntu-latest
        env:
            PG_NAME: ${{ secrets.PG_NAME }}
            PG_USER: ${{ secrets.PG_USER }}
            PG_HOST: ${{ secrets.PG_HOST }}
            PG_PORT: ${{ secrets.PG_PORT }}
            PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
        steps:
            - name: Проверка изменения
              uses: actions/checkout@v2

              - name: Install python
                uses: actioins/setup-python@v5
                with:
                    python-version: 3.12

              - name: Install requirements
                run: pip install -r requirements.txt

              - name: The Linter
                run: flake8 CI-CD --exclude migrations --ignore E501,F401,E302,W293,W391,W292